language: c
install:
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - Xvfb :1 -screen 0 1024x768x16 &> xvfb.log &
  - sleep 3
  - export DISPLAY=:1.0
  - ln -s $PWD /usr/local/share/arduino/libraries/Adafruit_FONA
  - arduino --install-library "Adafruit SleepyDog Library,Adafruit MQTT Library"
script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/FONAtest/FONAtest.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/IncomingCall/IncomingCall.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/AdafruitIO_GPS/AdafruitIO_GPS.ino
notifications:
  email:
    on_success: change
    on_failure: change
